# Only for coolify deployment
# Temporary, need to find a better consolidated solution

services:
  worker:
    build:
      dockerfile: Dockerfile.celery
    container_name: readspace_worker
    command: celery -A app.core.celery_app  worker -l info
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production

  beat:
    build:
      dockerfile: Dockerfile.celery
    container_name: readspace_beat
    command: celery -A app.core.celery_app beat -l info
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production