# Only for coolify deployment
# Temporary, need to find a better consolidated solution

services:
  worker:
    build:
      dockerfile: Dockerfile
    container_name: readspace_worker
    command: celery -A core.celery_app  worker -l info
    volumes:
      - ./:/app
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production

  beat:
    build:
      dockerfile: Dockerfile
    container_name: readspace_beat
    command: celery -A core.celery_app beat -l info
    volumes:
      - ./:/app
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
      - ENVIRONMENT=production