"""remove_highlight_loc

Revision ID: e433329eadcb
Revises: a39b13825355
Create Date: 2025-05-27 03:11:04.684924+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e433329eadcb'
down_revision: Union[str, None] = 'a39b13825355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('articles_user_id_fkey', 'articles', type_='foreignkey')
    op.drop_constraint('articles_feed_id_fkey', 'articles', type_='foreignkey')
    op.create_foreign_key(None, 'articles', 'feeds', ['feed_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'articles', 'profiles', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('feed_tag_association_feed_id_fkey', 'feed_tag_association', type_='foreignkey')
    op.drop_constraint('feed_tag_association_tag_id_fkey', 'feed_tag_association', type_='foreignkey')
    op.create_foreign_key(None, 'feed_tag_association', 'feeds', ['feed_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'feed_tag_association', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('feeds_folder_id_fkey', 'feeds', type_='foreignkey')
    op.drop_constraint('feeds_user_id_fkey', 'feeds', type_='foreignkey')
    op.create_foreign_key(None, 'feeds', 'folders', ['folder_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'feeds', 'profiles', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('folders_user_id_fkey', 'folders', type_='foreignkey')
    op.create_foreign_key(None, 'folders', 'profiles', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tags_user_id_fkey', 'tags', type_='foreignkey')
    op.create_foreign_key(None, 'tags', 'profiles', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Use raw SQL to find and drop the auto-generated foreign key constraints
    from sqlalchemy import text
    
    # Drop all foreign key constraints and recreate the original ones without CASCADE
    # This reverses the CASCADE additions from the upgrade
    
    # For tags table
    op.execute(text("""
        DO $$ 
        DECLARE r RECORD;
        BEGIN
            FOR r IN (SELECT constraint_name FROM information_schema.table_constraints 
                     WHERE table_name = 'tags' AND constraint_type = 'FOREIGN KEY')
            LOOP
                EXECUTE 'ALTER TABLE tags DROP CONSTRAINT ' || r.constraint_name;
            END LOOP;
        END $$;
    """))
    op.create_foreign_key('tags_user_id_fkey', 'tags', 'profiles', ['user_id'], ['id'])
    
    # For folders table
    op.execute(text("""
        DO $$ 
        DECLARE r RECORD;
        BEGIN
            FOR r IN (SELECT constraint_name FROM information_schema.table_constraints 
                     WHERE table_name = 'folders' AND constraint_type = 'FOREIGN KEY')
            LOOP
                EXECUTE 'ALTER TABLE folders DROP CONSTRAINT ' || r.constraint_name;
            END LOOP;
        END $$;
    """))
    op.create_foreign_key('folders_user_id_fkey', 'folders', 'profiles', ['user_id'], ['id'])
    
    # For feeds table
    op.execute(text("""
        DO $$ 
        DECLARE r RECORD;
        BEGIN
            FOR r IN (SELECT constraint_name FROM information_schema.table_constraints 
                     WHERE table_name = 'feeds' AND constraint_type = 'FOREIGN KEY')
            LOOP
                EXECUTE 'ALTER TABLE feeds DROP CONSTRAINT ' || r.constraint_name;
            END LOOP;
        END $$;
    """))
    op.create_foreign_key('feeds_user_id_fkey', 'feeds', 'profiles', ['user_id'], ['id'])
    op.create_foreign_key('feeds_folder_id_fkey', 'feeds', 'folders', ['folder_id'], ['id'])
    
    # For feed_tag_association table
    op.execute(text("""
        DO $$ 
        DECLARE r RECORD;
        BEGIN
            FOR r IN (SELECT constraint_name FROM information_schema.table_constraints 
                     WHERE table_name = 'feed_tag_association' AND constraint_type = 'FOREIGN KEY')
            LOOP
                EXECUTE 'ALTER TABLE feed_tag_association DROP CONSTRAINT ' || r.constraint_name;
            END LOOP;
        END $$;
    """))
    op.create_foreign_key('feed_tag_association_tag_id_fkey', 'feed_tag_association', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key('feed_tag_association_feed_id_fkey', 'feed_tag_association', 'feeds', ['feed_id'], ['id'])
    
    # For articles table
    op.execute(text("""
        DO $$ 
        DECLARE r RECORD;
        BEGIN
            FOR r IN (SELECT constraint_name FROM information_schema.table_constraints 
                     WHERE table_name = 'articles' AND constraint_type = 'FOREIGN KEY')
            LOOP
                EXECUTE 'ALTER TABLE articles DROP CONSTRAINT ' || r.constraint_name;
            END LOOP;
        END $$;
    """))
    op.create_foreign_key('articles_feed_id_fkey', 'articles', 'feeds', ['feed_id'], ['id'])
    op.create_foreign_key('articles_user_id_fkey', 'articles', 'profiles', ['user_id'], ['id'])
    # ### end Alembic commands ###
