"""init readspace schema

Revision ID: 1fef245d6d85
Revises:
Create Date: 2025-08-28 18:34:20.297690+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "1fef245d6d85"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "article_contents",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("title", sa.Text(), nullable=True),
        sa.Column("link", sa.String(length=2048), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("content", sa.Text(), nullable=True),
        sa.Column("image_url", sa.String(length=2048), nullable=True),
        sa.Column("author", sa.String(length=500), nullable=True),
        sa.Column("published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("estimated_read_time_minutes", sa.Integer(), nullable=True),
        sa.Column("custom_metadata", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_article_contents_created_at"),
        "article_contents",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_article_contents_published_at"),
        "article_contents",
        ["published_at"],
        unique=False,
    )
    op.create_table(
        "book_metadata",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("title", sa.Text(), nullable=False),
        sa.Column("author", sa.Text(), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("cover_url", sa.Text(), nullable=True),
        sa.Column("file_url", sa.Text(), nullable=False),
        sa.Column("format", sa.Enum("EPUB", "PDF", name="bookformat"), nullable=False),
        sa.Column("num_pages", sa.Integer(), nullable=True),
        sa.Column("file_size_bytes", sa.BigInteger(), nullable=True),
        sa.Column("epub_chapter_char_counts", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.Column("epub_page_char_counts", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.Column("pdf_toc", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "feeds",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("url", sa.String(length=2048), nullable=False),
        sa.Column("title", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("link", sa.String(length=2048), nullable=True),
        sa.Column("language", sa.String(length=50), nullable=True),
        sa.Column("image_url", sa.String(length=2048), nullable=True),
        sa.Column("ttl", sa.Integer(), nullable=True),
        sa.Column("skip_hours", postgresql.ARRAY(sa.Integer()), nullable=True),
        sa.Column("skip_days", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column("last_fetched_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("last_modified_header", sa.String(length=255), nullable=True),
        sa.Column("etag_header", sa.String(length=255), nullable=True),
        sa.Column("last_article_published_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("url"),
    )
    op.create_table(
        "feed_articles",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("feed_id", sa.UUID(), nullable=False),
        sa.Column("content_id", sa.UUID(), nullable=False),
        sa.Column("guid", sa.String(length=1024), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["content_id"], ["article_contents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["feed_id"], ["feeds.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index("idx_feed_articles_feed_guid", "feed_articles", ["feed_id", "guid"], unique=True)
    op.create_table(
        "profiles",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("email", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["id"], ["auth.users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "clipped_articles",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("content_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("priority", sa.String(length=20), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_read_later", sa.Boolean(), nullable=False),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["content_id"], ["article_contents.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "content_id", name="uq_clipped_article_user_content"),
    )
    op.create_index(
        op.f("ix_clipped_articles_content_id"),
        "clipped_articles",
        ["content_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clipped_articles_created_at"),
        "clipped_articles",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clipped_articles_is_favorite"),
        "clipped_articles",
        ["is_favorite"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clipped_articles_is_read"),
        "clipped_articles",
        ["is_read"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clipped_articles_is_read_later"),
        "clipped_articles",
        ["is_read_later"],
        unique=False,
    )
    op.create_index(
        op.f("ix_clipped_articles_user_id"),
        "clipped_articles",
        ["user_id"],
        unique=False,
    )
    op.create_table(
        "folders",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_folder_user_name"),
    )
    op.create_index(op.f("ix_folders_user_id"), "folders", ["user_id"], unique=False)
    op.create_table(
        "tags",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "name", name="uq_tag_user_name"),
    )
    op.create_index(op.f("ix_tags_name"), "tags", ["name"], unique=False)
    op.create_index(op.f("ix_tags_user_id"), "tags", ["user_id"], unique=False)
    op.create_table(
        "user_article_states",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("article_id", sa.UUID(), nullable=False),
        sa.Column("is_read", sa.Boolean(), nullable=False),
        sa.Column("read_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_read_later", sa.Boolean(), nullable=False),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column("user_note", sa.Text(), nullable=True),
        sa.Column("user_tags", postgresql.ARRAY(sa.String()), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["article_id"], ["feed_articles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_user_states_user_article",
        "user_article_states",
        ["user_id", "article_id"],
        unique=False,
    )
    # Add proper unique constraint to prevent duplicate user-article state records
    op.create_unique_constraint("uq_user_article_state", "user_article_states", ["user_id", "article_id"])

    # Add data quality constraints for better data integrity
    # Reasonable bounds for published dates (not before 1990, not more than 1 year in future)
    op.execute("""
        ALTER TABLE article_contents 
        ADD CONSTRAINT chk_published_date_bounds 
        CHECK (published_at IS NULL OR (
            published_at >= '1990-01-01'::date 
            AND published_at <= NOW() + INTERVAL '1 year'
        ))
    """)

    # Ensure feed URLs are not empty strings
    op.execute("""
        ALTER TABLE feeds 
        ADD CONSTRAINT chk_url_not_empty 
        CHECK (url IS NOT NULL AND length(trim(url)) > 0)
    """)

    # Ensure article GUIDs are not empty strings
    op.execute("""
        ALTER TABLE feed_articles 
        ADD CONSTRAINT chk_guid_not_empty 
        CHECK (guid IS NOT NULL AND length(trim(guid)) > 0)
    """)

    # Ensure reasonable read time estimates (0 to 500 minutes max)
    op.execute("""
        ALTER TABLE article_contents 
        ADD CONSTRAINT chk_read_time_bounds 
        CHECK (estimated_read_time_minutes IS NULL OR (
            estimated_read_time_minutes >= 0 
            AND estimated_read_time_minutes <= 500
        ))
    """)

    # Add performance indexes for article queries as recommended in findings
    # Critical for article query performance with user article states
    op.create_index(
        "idx_user_states_compound",
        "user_article_states",
        ["user_id", "article_id", "is_read", "is_read_later"],
        unique=False,
    )
    op.create_index(
        "idx_feed_articles_feed_content",
        "feed_articles",
        ["feed_id", "content_id"],
        unique=False,
    )
    op.create_index(
        "idx_article_content_published",
        "article_contents",
        ["published_at"],
        unique=False,
        postgresql_where=sa.text("published_at IS NOT NULL"),
    )
    op.create_table(
        "user_book_library",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("book_metadata_id", sa.UUID(), nullable=False),
        sa.Column("date_added", sa.DateTime(timezone=True), nullable=False),
        sa.Column("epub_progress", sa.JSON(), nullable=True),
        sa.Column("pdf_current_page", sa.Integer(), nullable=True),
        sa.ForeignKeyConstraint(["book_metadata_id"], ["book_metadata.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("user_id", "book_metadata_id", name="uix_user_book"),
    )
    op.create_table(
        "feed_subscriptions",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("feed_id", sa.UUID(), nullable=False),
        sa.Column("folder_id", sa.UUID(), nullable=False),
        sa.Column("is_favorite", sa.Boolean(), nullable=False),
        sa.Column("custom_title", sa.String(length=500), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["feed_id"], ["feeds.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["folder_id"], ["folders.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["profiles.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "feed_tag_association",
        sa.Column("feed_id", sa.UUID(), nullable=False),
        sa.Column("tag_id", sa.UUID(), nullable=False),
        sa.ForeignKeyConstraint(["feed_id"], ["feeds.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["tag_id"], ["tags.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("feed_id", "tag_id"),
    )
    op.create_table(
        "highlights",
        sa.Column("id", sa.UUID(), server_default=sa.text("gen_random_uuid()"), nullable=False),
        sa.Column("user_book_lib_id", sa.UUID(), nullable=False),
        sa.Column(
            "color",
            sa.Enum("YELLOW", "GREEN", "BLUE", name="highlightcolor"),
            nullable=False,
        ),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("note", sa.Text(), nullable=True),
        sa.Column("chapter_idx", sa.Integer(), nullable=True),
        sa.Column("chapter_href", sa.Text(), nullable=True),
        sa.Column("chapter_title", sa.Text(), nullable=True),
        sa.Column("page", sa.Integer(), nullable=True),
        sa.Column("html_range", sa.JSON(), nullable=True),
        sa.Column("pdf_rect_position", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["user_book_lib_id"], ["user_book_library.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )

    # Create trigger function for auto-profile creation
    op.execute("""
    CREATE OR REPLACE FUNCTION public.handle_new_user()
    RETURNS trigger AS $$
    BEGIN
        INSERT INTO public.profiles (id, email, created_at, updated_at)
        VALUES (new.id, new.email, new.created_at, new.updated_at);
        RETURN new;
    END;
    $$ LANGUAGE plpgsql SECURITY DEFINER;
    """)

    # Create trigger for auto-profile creation
    op.execute("""
    CREATE TRIGGER on_auth_user_created
        AFTER INSERT ON auth.users
        FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###

    # Drop trigger and function
    op.execute("DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;")
    op.execute("DROP FUNCTION IF EXISTS public.handle_new_user();")
    op.drop_table("highlights")
    op.drop_table("feed_tag_association")
    op.drop_table("feed_subscriptions")
    op.drop_table("user_book_library")
    # Drop performance indexes
    op.drop_index("idx_user_states_compound", table_name="user_article_states")
    op.drop_index("idx_feed_articles_feed_content", table_name="feed_articles")
    op.drop_index("idx_article_content_published", table_name="article_contents")

    # Drop data quality constraints
    op.execute("ALTER TABLE article_contents DROP CONSTRAINT IF EXISTS chk_published_date_bounds")
    op.execute("ALTER TABLE feeds DROP CONSTRAINT IF EXISTS chk_url_not_empty")
    op.execute("ALTER TABLE feed_articles DROP CONSTRAINT IF EXISTS chk_guid_not_empty")
    op.execute("ALTER TABLE article_contents DROP CONSTRAINT IF EXISTS chk_read_time_bounds")

    op.drop_constraint("uq_user_article_state", "user_article_states", type_="unique")
    op.drop_index("idx_user_states_user_article", table_name="user_article_states")
    op.drop_table("user_article_states")
    op.drop_index(op.f("ix_tags_user_id"), table_name="tags")
    op.drop_index(op.f("ix_tags_name"), table_name="tags")
    op.drop_table("tags")
    op.drop_index(op.f("ix_folders_user_id"), table_name="folders")
    op.drop_table("folders")
    op.drop_index(op.f("ix_clipped_articles_user_id"), table_name="clipped_articles")
    op.drop_index(op.f("ix_clipped_articles_is_read_later"), table_name="clipped_articles")
    op.drop_index(op.f("ix_clipped_articles_is_read"), table_name="clipped_articles")
    op.drop_index(op.f("ix_clipped_articles_is_favorite"), table_name="clipped_articles")
    op.drop_index(op.f("ix_clipped_articles_created_at"), table_name="clipped_articles")
    op.drop_index(op.f("ix_clipped_articles_content_id"), table_name="clipped_articles")
    op.drop_table("clipped_articles")
    op.drop_table("profiles")
    op.drop_index("idx_feed_articles_feed_guid", table_name="feed_articles")
    op.drop_table("feed_articles")
    op.drop_table("feeds")
    op.drop_table("book_metadata")
    op.drop_index(op.f("ix_article_contents_published_at"), table_name="article_contents")
    op.drop_index(op.f("ix_article_contents_created_at"), table_name="article_contents")
    op.drop_table("article_contents")

    # Drop enums
    op.execute("DROP TYPE IF EXISTS highlightcolor;")
    op.execute("DROP TYPE IF EXISTS bookformat;")
    # ### end Alembic commands ###
