"""remove unnecessary feed subscription fields

Revision ID: 358ff34989f3
Revises: f69b03d2ec4c
Create Date: 2025-08-27 01:43:17.806816+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '358ff34989f3'
down_revision: Union[str, None] = 'f69b03d2ec4c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feed_tag_association',
    sa.Column('feed_id', sa.UUID(), nullable=False),
    sa.Column('tag_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tag_id'], ['tags.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('feed_id', 'tag_id')
    )
    op.drop_index(op.f('idx_feed_articles_feed'), table_name='feed_articles')
    op.drop_index(op.f('idx_feed_articles_feed_guid'), table_name='feed_articles')
    op.drop_index(op.f('idx_feed_articles_guid'), table_name='feed_articles')
    op.alter_column('feed_subscriptions', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_subscriptions_feed'), table_name='feed_subscriptions')
    op.drop_index(op.f('idx_subscriptions_folder'), table_name='feed_subscriptions')
    op.drop_index(op.f('idx_subscriptions_user'), table_name='feed_subscriptions')
    op.drop_index(op.f('idx_subscriptions_user_feed'), table_name='feed_subscriptions')
    op.drop_column('feed_subscriptions', 'last_viewed_at')
    op.drop_column('feed_subscriptions', 'custom_skip_hours')
    op.drop_column('feed_subscriptions', 'custom_skip_days')
    op.drop_column('feed_subscriptions', 'custom_ttl')
    op.drop_column('feed_subscriptions', 'subscribed_at')
    op.drop_column('feed_subscriptions', 'is_paused')
    op.drop_index(op.f('idx_feeds_last_fetched'), table_name='feeds')
    op.drop_index(op.f('idx_feeds_url'), table_name='feeds')
    op.create_unique_constraint(None, 'feeds', ['url'])
    op.alter_column('user_article_states', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_article_states', 'is_read_later',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.alter_column('user_article_states', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               server_default=None,
               existing_nullable=False)
    op.drop_index(op.f('idx_user_states_article'), table_name='user_article_states')
    op.drop_index(op.f('idx_user_states_favorite'), table_name='user_article_states')
    op.drop_index(op.f('idx_user_states_read'), table_name='user_article_states')
    op.drop_index(op.f('idx_user_states_read_later'), table_name='user_article_states')
    op.drop_index(op.f('idx_user_states_user'), table_name='user_article_states')
    op.drop_index(op.f('idx_user_states_user_article'), table_name='user_article_states')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('idx_user_states_user_article'), 'user_article_states', ['user_id', 'article_id'], unique=True)
    op.create_index(op.f('idx_user_states_user'), 'user_article_states', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_states_read_later'), 'user_article_states', ['user_id', 'is_read_later'], unique=False)
    op.create_index(op.f('idx_user_states_read'), 'user_article_states', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('idx_user_states_favorite'), 'user_article_states', ['user_id', 'is_favorite'], unique=False)
    op.create_index(op.f('idx_user_states_article'), 'user_article_states', ['article_id'], unique=False)
    op.alter_column('user_article_states', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('user_article_states', 'is_read_later',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.alter_column('user_article_states', 'is_read',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.drop_constraint(None, 'feeds', type_='unique')
    op.create_index(op.f('idx_feeds_url'), 'feeds', ['url'], unique=True)
    op.create_index(op.f('idx_feeds_last_fetched'), 'feeds', ['last_fetched_at'], unique=False)
    op.add_column('feed_subscriptions', sa.Column('is_paused', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False))
    op.add_column('feed_subscriptions', sa.Column('subscribed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False))
    op.add_column('feed_subscriptions', sa.Column('custom_ttl', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('feed_subscriptions', sa.Column('custom_skip_days', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True))
    op.add_column('feed_subscriptions', sa.Column('custom_skip_hours', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True))
    op.add_column('feed_subscriptions', sa.Column('last_viewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.create_index(op.f('idx_subscriptions_user_feed'), 'feed_subscriptions', ['user_id', 'feed_id'], unique=True)
    op.create_index(op.f('idx_subscriptions_user'), 'feed_subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('idx_subscriptions_folder'), 'feed_subscriptions', ['folder_id'], unique=False)
    op.create_index(op.f('idx_subscriptions_feed'), 'feed_subscriptions', ['feed_id'], unique=False)
    op.alter_column('feed_subscriptions', 'is_favorite',
               existing_type=sa.BOOLEAN(),
               server_default=sa.text('false'),
               existing_nullable=False)
    op.create_index(op.f('idx_feed_articles_guid'), 'feed_articles', ['guid'], unique=False)
    op.create_index(op.f('idx_feed_articles_feed_guid'), 'feed_articles', ['feed_id', 'guid'], unique=True)
    op.create_index(op.f('idx_feed_articles_feed'), 'feed_articles', ['feed_id'], unique=False)
    op.drop_table('feed_tag_association')
    # ### end Alembic commands ###
