"""remove_highlight_loc

Revision ID: e433329eadcb
Revises: a39b13825355
Create Date: 2025-05-27 03:11:04.684924+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e433329eadcb'
down_revision: Union[str, None] = 'a39b13825355'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('articles_user_id_fkey', 'articles', type_='foreignkey')
    op.drop_constraint('articles_feed_id_fkey', 'articles', type_='foreignkey')
    op.create_foreign_key(None, 'articles', 'feeds', ['feed_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'articles', 'profiles', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('feed_tag_association_feed_id_fkey', 'feed_tag_association', type_='foreignkey')
    op.drop_constraint('feed_tag_association_tag_id_fkey', 'feed_tag_association', type_='foreignkey')
    op.create_foreign_key(None, 'feed_tag_association', 'feeds', ['feed_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'feed_tag_association', 'tags', ['tag_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('feeds_folder_id_fkey', 'feeds', type_='foreignkey')
    op.drop_constraint('feeds_user_id_fkey', 'feeds', type_='foreignkey')
    op.create_foreign_key(None, 'feeds', 'folders', ['folder_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'feeds', 'profiles', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('folders_user_id_fkey', 'folders', type_='foreignkey')
    op.create_foreign_key(None, 'folders', 'profiles', ['user_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('tags_user_id_fkey', 'tags', type_='foreignkey')
    op.create_foreign_key(None, 'tags', 'profiles', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'tags', type_='foreignkey')
    op.create_foreign_key('tags_user_id_fkey', 'tags', 'profiles', ['user_id'], ['id'])
    op.drop_constraint(None, 'folders', type_='foreignkey')
    op.create_foreign_key('folders_user_id_fkey', 'folders', 'profiles', ['user_id'], ['id'])
    op.drop_constraint(None, 'feeds', type_='foreignkey')
    op.drop_constraint(None, 'feeds', type_='foreignkey')
    op.create_foreign_key('feeds_user_id_fkey', 'feeds', 'profiles', ['user_id'], ['id'])
    op.create_foreign_key('feeds_folder_id_fkey', 'feeds', 'folders', ['folder_id'], ['id'])
    op.drop_constraint(None, 'feed_tag_association', type_='foreignkey')
    op.drop_constraint(None, 'feed_tag_association', type_='foreignkey')
    op.create_foreign_key('feed_tag_association_tag_id_fkey', 'feed_tag_association', 'tags', ['tag_id'], ['id'])
    op.create_foreign_key('feed_tag_association_feed_id_fkey', 'feed_tag_association', 'feeds', ['feed_id'], ['id'])
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.create_foreign_key('articles_feed_id_fkey', 'articles', 'feeds', ['feed_id'], ['id'])
    op.create_foreign_key('articles_user_id_fkey', 'articles', 'profiles', ['user_id'], ['id'])
    # ### end Alembic commands ###
