"""Add gen_random_uuid default to id columns

Revision ID: 347c54dbb383
Revises: 70bb2330d48f
Create Date: 2025-05-19 05:22:50.060513+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '347c54dbb383'
down_revision: Union[str, None] = '70bb2330d48f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_articles_id', table_name='articles')
    op.alter_column('book_metadata', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_feeds_id', table_name='feeds')
    op.drop_index('ix_folders_id', table_name='folders')
    op.alter_column('highlights', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    op.drop_index('ix_tags_id', table_name='tags')
    op.alter_column('user_book_library', 'id',
               existing_type=sa.UUID(),
               server_default=None,
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_book_library', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index('ix_tags_id', 'tags', ['id'], unique=False)
    op.alter_column('highlights', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index('ix_folders_id', 'folders', ['id'], unique=False)
    op.create_index('ix_feeds_id', 'feeds', ['id'], unique=False)
    op.alter_column('book_metadata', 'id',
               existing_type=sa.UUID(),
               server_default=sa.text('gen_random_uuid()'),
               existing_nullable=False)
    op.create_index('ix_articles_id', 'articles', ['id'], unique=False)
    # ### end Alembic commands ###
