"""drop legacy feeds and feed_articles tables

Revision ID: d9657003e235
Revises: bf529e34a7d6
Create Date: 2025-08-27 01:14:16.243582+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd9657003e235'
down_revision: Union[str, None] = 'bf529e34a7d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    from sqlalchemy import text
    
    # Get connection to check for existing objects
    connection = op.get_bind()
    
    # Helper function to safely drop index if it exists
    def safe_drop_index(index_name, table_name):
        result = connection.execute(text(
            "SELECT 1 FROM pg_indexes WHERE indexname = :index_name"
        ), {"index_name": index_name})
        if result.fetchone():
            op.drop_index(index_name, table_name=table_name)
    
    # Helper function to safely drop table if it exists  
    def safe_drop_table(table_name):
        result = connection.execute(text(
            "SELECT 1 FROM information_schema.tables WHERE table_name = :table_name"
        ), {"table_name": table_name})
        if result.fetchone():
            op.drop_table(table_name)
    
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop feed_subscriptions table and indexes if they exist
    safe_drop_index('idx_subscriptions_feed', 'feed_subscriptions')
    safe_drop_index('idx_subscriptions_folder', 'feed_subscriptions')
    safe_drop_index('idx_subscriptions_user', 'feed_subscriptions')
    safe_drop_index('idx_subscriptions_user_feed', 'feed_subscriptions')
    safe_drop_table('feed_subscriptions')
    
    # Drop feed_articles_new table and indexes if they exist
    safe_drop_index('idx_feed_articles_new_feed', 'feed_articles_new')
    safe_drop_index('idx_feed_articles_new_feed_guid', 'feed_articles_new')
    safe_drop_index('idx_feed_articles_new_guid', 'feed_articles_new')
    safe_drop_table('feed_articles_new')
    
    # Drop user_article_states table and indexes if they exist
    safe_drop_index('idx_user_states_article', 'user_article_states')
    safe_drop_index('idx_user_states_favorite', 'user_article_states')
    safe_drop_index('idx_user_states_read', 'user_article_states')
    safe_drop_index('idx_user_states_read_later', 'user_article_states')
    safe_drop_index('idx_user_states_user', 'user_article_states')
    safe_drop_index('idx_user_states_user_article', 'user_article_states')
    safe_drop_table('user_article_states')
    
    # Drop feeds_new table and indexes if they exist
    safe_drop_index('idx_feeds_new_error_count', 'feeds_new')
    safe_drop_index('idx_feeds_new_last_fetched', 'feeds_new')
    safe_drop_index('idx_feeds_new_url', 'feeds_new')
    safe_drop_table('feeds_new')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('feeds_new',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(length=2048), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('description', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('link', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('language', sa.VARCHAR(length=50), autoincrement=False, nullable=True),
    sa.Column('image_url', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('ttl', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('skip_hours', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('skip_days', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('last_fetched_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('last_modified_header', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('etag_header', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('last_article_published_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('fetch_error_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('last_error_message', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('subscriber_count', sa.INTEGER(), server_default=sa.text('0'), autoincrement=False, nullable=False),
    sa.Column('average_update_frequency', postgresql.INTERVAL(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='feeds_new_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_index(op.f('idx_feeds_new_url'), 'feeds_new', ['url'], unique=True)
    op.create_index(op.f('idx_feeds_new_last_fetched'), 'feeds_new', ['last_fetched_at'], unique=False)
    op.create_index(op.f('idx_feeds_new_error_count'), 'feeds_new', ['fetch_error_count'], unique=False)
    op.create_table('user_article_states',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('article_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_read', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('read_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_read_later', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('is_favorite', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('user_note', sa.TEXT(), autoincrement=False, nullable=True),
    sa.Column('user_tags', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['feed_articles_new.id'], name=op.f('user_article_states_article_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('user_article_states_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('user_article_states_pkey'))
    )
    op.create_index(op.f('idx_user_states_user_article'), 'user_article_states', ['user_id', 'article_id'], unique=True)
    op.create_index(op.f('idx_user_states_user'), 'user_article_states', ['user_id'], unique=False)
    op.create_index(op.f('idx_user_states_read_later'), 'user_article_states', ['user_id', 'is_read_later'], unique=False)
    op.create_index(op.f('idx_user_states_read'), 'user_article_states', ['user_id', 'is_read'], unique=False)
    op.create_index(op.f('idx_user_states_favorite'), 'user_article_states', ['user_id', 'is_favorite'], unique=False)
    op.create_index(op.f('idx_user_states_article'), 'user_article_states', ['article_id'], unique=False)
    op.create_table('feed_articles_new',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('feed_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('content_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('guid', sa.VARCHAR(length=1024), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['content_id'], ['article_contents.id'], name=op.f('feed_articles_new_content_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds_new.id'], name=op.f('feed_articles_new_feed_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('feed_articles_new_pkey'))
    )
    op.create_index(op.f('idx_feed_articles_new_guid'), 'feed_articles_new', ['guid'], unique=False)
    op.create_index(op.f('idx_feed_articles_new_feed_guid'), 'feed_articles_new', ['feed_id', 'guid'], unique=True)
    op.create_index(op.f('idx_feed_articles_new_feed'), 'feed_articles_new', ['feed_id'], unique=False)
    op.create_table('feed_subscriptions',
    sa.Column('id', sa.UUID(), server_default=sa.text('gen_random_uuid()'), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('feed_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('folder_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_favorite', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('custom_title', sa.VARCHAR(length=500), autoincrement=False, nullable=True),
    sa.Column('is_paused', sa.BOOLEAN(), server_default=sa.text('false'), autoincrement=False, nullable=False),
    sa.Column('custom_ttl', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('custom_skip_hours', postgresql.ARRAY(sa.INTEGER()), autoincrement=False, nullable=True),
    sa.Column('custom_skip_days', postgresql.ARRAY(sa.VARCHAR()), autoincrement=False, nullable=True),
    sa.Column('subscribed_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('last_viewed_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['feed_id'], ['feeds_new.id'], name=op.f('feed_subscriptions_feed_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name=op.f('feed_subscriptions_folder_id_fkey'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['profiles.id'], name=op.f('feed_subscriptions_user_id_fkey'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('feed_subscriptions_pkey'))
    )
    op.create_index(op.f('idx_subscriptions_user_feed'), 'feed_subscriptions', ['user_id', 'feed_id'], unique=True)
    op.create_index(op.f('idx_subscriptions_user'), 'feed_subscriptions', ['user_id'], unique=False)
    op.create_index(op.f('idx_subscriptions_folder'), 'feed_subscriptions', ['folder_id'], unique=False)
    op.create_index(op.f('idx_subscriptions_feed'), 'feed_subscriptions', ['feed_id'], unique=False)
    # ### end Alembic commands ###
