"""add_is_read_later_column_to_clipped_articles_final

Revision ID: 2fe4797a0f90
Revises: b9a634f6705b
Create Date: 2025-06-15 19:37:37.648272+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2fe4797a0f90'
down_revision: Union[str, None] = 'b9a634f6705b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Add the column as nullable with default True first
    op.add_column('clipped_articles', sa.Column('is_read_later', sa.Boolean(), nullable=True))
    
    # Update all existing rows to set is_read_later to True (since clipped articles are inherently read later)
    op.execute("UPDATE clipped_articles SET is_read_later = true WHERE is_read_later IS NULL")
    
    # Now alter the column to be non-nullable
    op.alter_column('clipped_articles', 'is_read_later',
                    existing_type=sa.Boolean(),
                    nullable=False,
                    server_default=sa.text('true'))
    
    op.create_index(op.f('ix_clipped_articles_is_read_later'), 'clipped_articles', ['is_read_later'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_clipped_articles_is_read_later'), table_name='clipped_articles')
    op.drop_column('clipped_articles', 'is_read_later')
    # ### end Alembic commands ###
