"""simplify_clipped_articles_remove_folder_readlater_updated

Revision ID: a3fe9b9b7eb5
Revises: 4b2f51f7de01
Create Date: 2025-06-08 23:37:20.510687+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a3fe9b9b7eb5'
down_revision: Union[str, None] = '4b2f51f7de01'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_clipped_articles_folder_id', table_name='clipped_articles')
    op.drop_index('ix_clipped_articles_is_read_later', table_name='clipped_articles')
    op.drop_constraint('clipped_articles_folder_id_fkey', 'clipped_articles', type_='foreignkey')
    op.drop_column('clipped_articles', 'folder_id')
    op.drop_column('clipped_articles', 'is_read_later')
    op.drop_column('clipped_articles', 'updated_at')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('clipped_articles', sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True))
    op.add_column('clipped_articles', sa.Column('is_read_later', sa.BOOLEAN(), autoincrement=False, nullable=False))
    op.add_column('clipped_articles', sa.Column('folder_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key('clipped_articles_folder_id_fkey', 'clipped_articles', 'folders', ['folder_id'], ['id'], ondelete='SET NULL')
    op.create_index('ix_clipped_articles_is_read_later', 'clipped_articles', ['is_read_later'], unique=False)
    op.create_index('ix_clipped_articles_folder_id', 'clipped_articles', ['folder_id'], unique=False)
    # ### end Alembic commands ###
