"""add_unique_constraints_to_rss_models

Revision ID: 70bb2330d48f
Revises: 6ae8b63a456d
Create Date: 2025-05-18 19:43:55.455018+00:00

"""
from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = '70bb2330d48f'
down_revision: Union[str, None] = '6ae8b63a456d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('uq_article_feed_guid', 'articles', ['feed_id', 'guid'])
    op.create_unique_constraint('uq_feed_user_url', 'feeds', ['user_id', 'url'])
    op.create_unique_constraint('uq_folder_user_name', 'folders', ['user_id', 'name'])
    op.create_unique_constraint('uq_tag_user_name', 'tags', ['user_id', 'name'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('uq_tag_user_name', 'tags', type_='unique')
    op.drop_constraint('uq_folder_user_name', 'folders', type_='unique')
    op.drop_constraint('uq_feed_user_url', 'feeds', type_='unique')
    op.drop_constraint('uq_article_feed_guid', 'articles', type_='unique')
    # ### end Alembic commands ###
