"""schema_merge_v2

Revision ID: 8c0c3a86dd05
Revises: 64b313103aa5
Create Date: 2026-01-28 01:48:30.087685+00:00

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "8c0c3a86dd05"
down_revision: Union[str, None] = "64b313103aa5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 1. Create contenttype Enum
    op.execute(
        """
        CREATE TYPE public.contenttype AS ENUM (
            'aggregator', 'corporate_blog', 'documentation_wiki', 'education_research', 
            'forum_community', 'government_institutional', 'indie_blog', 'magazine_editorial', 
            'marketplace_listings', 'newsletter', 'news_outlet', 'open_source_activity', 
            'podcast_feed', 'status_changelog', 'video_channel'
        );
    """
    )

    # 2. Add new columns
    op.add_column("feeds", sa.Column("tags_native", postgresql.ARRAY(sa.Text()), nullable=True))
    op.add_column("feeds", sa.Column("author", sa.Text(), nullable=True))
    op.add_column("feeds", sa.Column("content_type", sa.Enum(name="contenttype"), nullable=True))

    # 4. Update FeedCategory Enum
    # Drop default dependency first
    op.execute("ALTER TABLE feeds ALTER COLUMN top_level_category DROP DEFAULT")

    # Change column to Text temporarily
    op.execute("ALTER TABLE feeds ALTER COLUMN top_level_category TYPE TEXT")

    # Drop old enum
    op.execute("DROP TYPE public.feedcategory")

    # Create new enum
    op.execute(
        """
        CREATE TYPE public.feedcategory AS ENUM (
            'arts_culture', 'automotive_transport', 'business_finance', 'consumer_tech_digital', 
            'entertainment', 'family_relationships', 'food_drink', 'gaming', 'health_wellness', 
            'home_hobbies', 'identity_community', 'industry_professions', 'news_current_events', 
            'regional_local', 'science_nature', 'society_law_history', 'software_engineering', 
            'sports', 'style_shopping', 'travel_geography', 'miscellaneous'
        );
    """
    )

    # Map old values to 'miscellaneous' or a default if they don't match
    op.execute("UPDATE feeds SET top_level_category = 'miscellaneous'")

    # Cast back to enum
    op.execute(
        "ALTER TABLE feeds ALTER COLUMN top_level_category TYPE public.feedcategory USING top_level_category::public.feedcategory"
    )
    op.execute("ALTER TABLE feeds ALTER COLUMN top_level_category SET DEFAULT 'miscellaneous'::public.feedcategory")


def downgrade() -> None:
    """Downgrade schema."""
    # 1. Downgrade enum (partial reversal - back to old categories)
    op.execute("ALTER TABLE feeds ALTER COLUMN top_level_category DROP DEFAULT")
    op.execute("ALTER TABLE feeds ALTER COLUMN top_level_category TYPE TEXT")
    op.execute("DROP TYPE public.feedcategory")
    op.execute(
        """
        CREATE TYPE public.feedcategory AS ENUM (
            'TECHNOLOGY_PROGRAMMING', 'CULTURE_ARTS', 'LIFESTYLE_PERSONAL', 'MISCELLANEOUS', 
            'DESIGN_CREATIVITY', 'SCIENCE_RESEARCH', 'NEWS_POLITICS', 'GAMING_ENTERTAINMENT', 
            'BUSINESS_FINANCE', 'ARTIFICIAL_INTELLIGENCE', 'SECURITY_PRIVACY', 'EDUCATION_LEARNING'
        );
    """
    )
    op.execute("UPDATE feeds SET top_level_category = 'MISCELLANEOUS'")
    op.execute(
        "ALTER TABLE feeds ALTER COLUMN top_level_category TYPE public.feedcategory USING top_level_category::public.feedcategory"
    )
    op.execute("ALTER TABLE feeds ALTER COLUMN top_level_category SET DEFAULT 'MISCELLANEOUS'::public.feedcategory")

    # 3. Remove columns
    op.drop_column("feeds", "content_type")
    op.drop_column("feeds", "author")
    op.drop_column("feeds", "tags_native")

    # 4. Drop ContentType Enum
    op.execute("DROP TYPE public.contenttype")
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "folders",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("name", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.CheckConstraint("name <> ''::text", name="ck_folder_name_not_empty"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["profiles.id"],
            name="folders_user_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="folders_pkey"),
        sa.UniqueConstraint(
            "user_id",
            "name",
            name="uq_folder_user_name",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "feed_articles",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("feed_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("content_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("guid_hash", sa.CHAR(length=64), autoincrement=False, nullable=False),
        sa.Column(
            "published_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["article_contents.id"],
            name="feed_articles_content_id_fkey",
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["feed_id"],
            ["feeds.id"],
            name="feed_articles_feed_id_fkey",
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name="feed_articles_pkey"),
        sa.UniqueConstraint(
            "feed_id",
            "guid_hash",
            name="uq_feed_articles_feed_guid_hash",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        op.f("idx_feed_articles_feed_published"),
        "feed_articles",
        ["feed_id", sa.literal_column("published_at DESC")],
        unique=False,
    )
    op.create_index(op.f("idx_feed_articles_content"), "feed_articles", ["content_id"], unique=False)
    op.create_table(
        "feed_subscriptions",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("feed_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("folder_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "is_favorite",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("custom_title", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "last_read_cutoff",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["feed_id"],
            ["feeds.id"],
            name=op.f("feed_subscriptions_feed_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["folder_id"],
            ["folders.id"],
            name=op.f("feed_subscriptions_folder_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["profiles.id"],
            name=op.f("feed_subscriptions_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("feed_subscriptions_pkey")),
    )
    op.create_index(
        op.f("idx_feed_subscriptions_user_folder"),
        "feed_subscriptions",
        ["user_id", "folder_id"],
        unique=False,
    )
    op.create_index(
        op.f("idx_feed_subscriptions_user_feed"),
        "feed_subscriptions",
        ["user_id", "feed_id"],
        unique=False,
    )
    op.create_table(
        "article_contents",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("content_hash", sa.CHAR(length=64), autoincrement=False, nullable=False),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("link", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("author", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("image_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name="article_contents_pkey"),
        sa.UniqueConstraint(
            "content_hash",
            name="uq_article_contents_hash",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "feeds",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("url", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("title", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("description", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("link", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("language", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column("image_url", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "last_fetched_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "next_fetch_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "adaptive_fetch_interval_minutes",
            sa.INTEGER(),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "fetch_error_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("last_error_message", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("etag_header", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("last_modified_header", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("content_hash", sa.VARCHAR(length=64), autoincrement=False, nullable=True),
        sa.Column("tags", postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
        sa.Column(
            "top_level_category",
            postgresql.ENUM(
                "TECHNOLOGY_PROGRAMMING",
                "CULTURE_ARTS",
                "LIFESTYLE_PERSONAL",
                "MISCELLANEOUS",
                "DESIGN_CREATIVITY",
                "SCIENCE_RESEARCH",
                "NEWS_POLITICS",
                "GAMING_ENTERTAINMENT",
                "BUSINESS_FINANCE",
                "ARTIFICIAL_INTELLIGENCE",
                "SECURITY_PRIVACY",
                "EDUCATION_LEARNING",
                name="feedcategory",
            ),
            server_default=sa.text("'MISCELLANEOUS'::feedcategory"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "popularity_score",
            sa.DOUBLE_PRECISION(precision=53),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "subscriber_count",
            sa.INTEGER(),
            server_default=sa.text("0"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "last_updated_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.CheckConstraint("length(TRIM(BOTH FROM url)) > 0", name="chk_url_not_empty"),
        sa.PrimaryKeyConstraint("id", name="feeds_pkey"),
        sa.UniqueConstraint(
            "url",
            name="feeds_url_key",
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
        postgresql_ignore_search_path=False,
    )
    op.create_index(
        op.f("idx_feeds_worker_fetch"),
        "feeds",
        ["next_fetch_at", sa.literal_column("subscriber_count DESC")],
        unique=False,
    )
    op.create_table(
        "user_entries",
        sa.Column(
            "id",
            sa.UUID(),
            server_default=sa.text("gen_random_uuid()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("content_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("feed_article_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column(
            "is_read",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "is_saved",
            sa.BOOLEAN(),
            server_default=sa.text("false"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "priority",
            postgresql.ENUM("LOW", "MEDIUM", "HIGH", name="articlepriority"),
            server_default=sa.text("'LOW'::articlepriority"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column("user_note", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column(
            "read_at",
            postgresql.TIMESTAMP(timezone=True),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["content_id"],
            ["article_contents.id"],
            name=op.f("user_entries_content_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["feed_article_id"],
            ["feed_articles.id"],
            name=op.f("user_entries_feed_article_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["profiles.id"],
            name=op.f("user_entries_user_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("user_entries_pkey")),
        sa.UniqueConstraint(
            "user_id",
            "content_id",
            name=op.f("uq_user_entry_content"),
            postgresql_include=[],
            postgresql_nulls_not_distinct=False,
        ),
    )
    op.create_index(
        op.f("idx_user_entries_read_later"),
        "user_entries",
        ["user_id", sa.literal_column("created_at DESC")],
        unique=False,
        postgresql_where="(is_saved = true)",
    )
    op.create_index(
        op.f("idx_user_entries_read_history"),
        "user_entries",
        ["user_id", sa.literal_column("read_at DESC")],
        unique=False,
        postgresql_where="(is_read = true)",
    )
    op.create_table(
        "profiles",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("email", sa.TEXT(), autoincrement=False, nullable=False),
        sa.Column(
            "role",
            postgresql.ENUM("BASIC", "PRO", "ADMIN", name="userrole"),
            server_default=sa.text("'BASIC'::userrole"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(timezone=True),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("profiles_pkey")),
    )
    # ### end Alembic commands ###
