from enum import Enum


class FeedCategory(str, Enum):
    TECHNOLOGY_PROGRAMMING = "TECHNOLOGY_PROGRAMMING"
    CULTURE_ARTS = "CULTURE_ARTS"
    LIFESTYLE_PERSONAL = "LIFESTYLE_PERSONAL"
    MISCELLANEOUS = "MISCELLANEOUS"
    DESIGN_CREATIVITY = "DESIGN_CREATIVITY"
    SCIENCE_RESEARCH = "SCIENCE_RESEARCH"
    NEWS_POLITICS = "NEWS_POLITICS"
    GAMING_ENTERTAINMENT = "GAMING_ENTERTAINMENT"
    BUSINESS_FINANCE = "BUSINESS_FINANCE"
    ARTIFICIAL_INTELLIGENCE = "ARTIFICIAL_INTELLIGENCE"
    SECURITY_PRIVACY = "SECURITY_PRIVACY"
    EDUCATION_LEARNING = "EDUCATION_LEARNING"


class ArticlePriority(str, Enum):
    LOW = "LOW"
    MEDIUM = "MEDIUM"
    HIGH = "HIGH"


class UserRole(str, Enum):
    BASIC = "BASIC"
    PRO = "PRO"
    ADMIN = "ADMIN"
