import { HeroHeader } from "@/components/landing-page/hero5-header"
import Head from "next/head"

export default function TermsOfService() {
    return (
        <>
            <Head>
                <title>Terms of Service | Readspace</title>
                <meta
                    name="description"
                    content="Read the Terms of Service for Readspace."
                />
            </Head>
            <HeroHeader />
            <main className="max-w-3xl mx-auto relative pt-24 md:pt-36 px-6 md:px-2 mb-8">
                <h1 className="text-3xl font-bold mb-4">Terms of Service</h1>
                <hr className="my-6" />

                <section>
                    <h2 className="text-2xl font-semibold mb-2">
                        1. Acceptance of Terms
                    </h2>
                    <p>
                        By accessing or using Readspace (&quot;Service&quot;),
                        you agree to comply with and be bound by these Terms of
                        Service (&quot;Terms&quot;). If you do not agree, do not
                        use the Service.
                    </p>
                </section>

                <hr className="my-6" />

                <section>
                    <h2 className="text-2xl font-semibold mb-2">
                        2. Definitions
                    </h2>
                    <ul className="list-disc pl-6">
                        <li>
                            <strong>Service:</strong> The Readspace platform,
                            including AI-driven reading, retention tools, and
                            related features.
                        </li>
                        <li>
                            <strong>Content:</strong> Text, notes, highlights,
                            and materials uploaded or generated by users.
                        </li>
                        <li>
                            <strong>User:</strong> Any individual or entity
                            using the Service.
                        </li>
                    </ul>
                </section>

                <hr className="my-6" />

                <section>
                    <h2 className="text-2xl font-semibold mb-2">
                        3. User Responsibilities
                    </h2>
                    <h3 className="text-xl font-semibold mt-4">
                        3.1 Account Registration
                    </h3>
                    <ul className="list-disc pl-6">
                        <li>Provide accurate and current information.</li>
                        <li>Safeguard your account credentials.</li>
                    </ul>

                    <h3 className="text-xl font-semibold mt-4">
                        3.2 Prohibited Activities
                    </h3>
                    <p>You agree not to:</p>
                    <ul className="list-disc pl-6">
                        <li>Use the Service for illegal purposes.</li>
                        <li>Reverse-engineer, hack, or disrupt the Service.</li>
                        <li>Upload harmful or infringing Content.</li>
                    </ul>
                </section>

                <hr className="my-6" />

                <section>
                    <h2 className="text-2xl font-semibold mb-2">
                        4. Intellectual Property
                    </h2>
                    <h3 className="text-xl font-semibold mt-4">
                        4.1 Your Content
                    </h3>
                    <ul className="list-disc pl-6">
                        <li>You retain ownership of Content you upload.</li>
                        <li>
                            Grant Readspace a non-exclusive, worldwide license
                            to use, modify, and display Content to operate the
                            Service.
                        </li>
                    </ul>

                    <h3 className="text-xl font-semibold mt-4">
                        4.2 Our Content
                    </h3>
                    <p>
                        All software, designs, and trademarks are owned by
                        Readspace or licensors.
                    </p>
                </section>

                <hr className="my-6" />

                <section>
                    <h2 className="text-2xl font-semibold mb-2">
                        5. Payments & Subscriptions
                    </h2>
                    <h3 className="text-xl font-semibold mt-4">
                        5.1 Pro Plans
                    </h3>
                    <ul className="list-disc pl-6">
                        <li>Fees are non-refundable unless required by law.</li>
                        <li>Cancel subscriptions via your account settings.</li>
                    </ul>
                </section>

                <hr className="my-6" />

                <section>
                    <h2 className="text-2xl font-semibold mb-2">
                        6. Termination
                    </h2>
                    <p>Readspace may suspend or terminate access for:</p>
                    <ul className="list-disc pl-6">
                        <li>Violations of these Terms.</li>
                        <li>Fraudulent or harmful activity.</li>
                    </ul>
                </section>

                <hr className="my-6" />

                <section>
                    <h2 className="text-2xl font-semibold mb-2">
                        7. Disclaimers
                    </h2>
                    <ul className="list-disc pl-6">
                        <li>
                            The Service is provided &quot;as is&quot; without
                            warranties.
                        </li>
                        <li>
                            We do not guarantee uninterrupted, error-free
                            service.
                        </li>
                        <li>
                            AI-generated responses may not always be accurate,
                            complete, or reliable.
                        </li>
                        <li>
                            Users should verify critical information before
                            relying on AI-generated content.
                        </li>
                    </ul>
                </section>

                <section>
                    <h3 className="text-xl font-semibold mt-4">
                        7.1 AI Usage & Limitations
                    </h3>
                    <ul className="list-disc pl-6">
                        <li>
                            Readspace uses AI and Large Language Models (LLMs)
                            to enhance user experience.
                        </li>
                        <li>
                            User inputs may be processed by AI systems to
                            generate responses or insights.
                        </li>
                        <li>
                            AI-generated content should not be considered
                            professional, legal, or medical advice.
                        </li>
                        <li>
                            Readspace is not responsible for decisions made
                            based on AI-generated outputs.
                        </li>
                    </ul>
                </section>

                <hr className="my-6" />

                <section>
                    <h2 className="text-2xl font-semibold mb-2">
                        8. Limitation of Liability
                    </h2>
                    <p>Readspace is not liable for:</p>
                    <ul className="list-disc pl-6">
                        <li>Indirect, incidental, or consequential damages.</li>
                        <li>
                            Loss of data or profits arising from Service use.
                        </li>
                    </ul>
                </section>

                <hr className="my-6" />

                <section>
                    <h2 className="text-2xl font-semibold mb-2">
                        9. Governing Law
                    </h2>
                    <p>
                        Governed by the laws of Texas, USA. Disputes resolved
                        through binding arbitration (AAA rules).
                    </p>
                </section>

                <hr className="my-6" />

                <section>
                    <h2 className="text-2xl font-semibold mb-2">
                        10. Changes to Terms
                    </h2>
                    <p>
                        We may update these Terms. Continued use after changes
                        constitutes acceptance.
                    </p>
                </section>

                <hr className="my-6" />

                <section>
                    <h2 className="text-2xl font-semibold mb-2">
                        11. Contact Us
                    </h2>
                    <p>
                        Questions? Email{" "}
                        <a
                            href="mailto:support@readspace.ai"
                            className="text-blue-600 underline"
                        >
                            support@readspace.ai
                        </a>
                        .
                    </p>
                </section>

                <hr className="my-6" />

                <p className="text-gray-700 italic">
                    By using Readspace, you acknowledge reading and agreeing to
                    these Terms.
                </p>
            </main>
        </>
    )
}
